from . import product_template
from . import account_move
from . import application
from . import res_partner
from . import subscription
from . import sale_subscription_line
from . import res_config_settings
from . import product_attribute
from . import product_attribute_value
