name: tests

on:
  pull_request:
    branches:
      - "18.0"
  push:
    branches:
      - "18.0"

jobs:
  test:
    runs-on: ubuntu-22.04
    container: ghcr.io/oca/oca-ci/py3.10-odoo18.0:latest
    name: Odoo
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: odoo
          POSTGRES_PASSWORD: odoo
          POSTGRES_DB: odoo
        ports:
          - 5432:5432
    env:
      OCA_ENABLE_CHECKLOG_ODOO: "1"
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Aggregate repos.yaml
        run: |
          set -x
          pip install git-aggregator
          gitaggregate -c repos.yaml
          addons_path=$ADDONS_PATH,$(find $(pwd)/* -name .git -exec dirname {} \; | uniq | tr '\n' ',' | sed 's/,$//'),.
          echo "addons_path=${addons_path}" >> ${ODOO_RC}
          echo "ADDONS_PATH=$addons_path" >> $GITHUB_ENV
      - name: Install external dependencies
        run: |
          selection_flags=$(echo $ADDONS_PATH | sed 's/,/ -d /g' | sed 's/^/-d /')
          external_deps=$(manifestoo $selection_flags --exclude-core-addons list-external-dependencies python --transitive --separator ' ')
          pip3 install $external_deps pdfminer.six==20220319
      - name: Check licenses
        run: manifestoo -d . check-dev-status --default-dev-status=Beta
      - name: Initialize test db
        run: oca_init_test_database
      - name: Run tests
        run: oca_run_tests
      - name: Upload screenshots from JS tests
        uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: Screenshots of failed JS tests - ${{ matrix.name }}${{ join(matrix.include) }}
          path: /tmp/odoo_tests/${{ env.PGDATABASE }}
          if-no-files-found: ignore
